/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cs300_MessageJNI */

#ifndef _Included_edu_cs300_MessageJNI
#define _Included_edu_cs300_MessageJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_cs300_MessageJNI
 * Method:    writePlayerFinalStatsMsg
 * Signature: (IIILjava/lang/String;IIIIIIDD)V
 */
JNIEXPORT void JNICALL Java_edu_cs300_MessageJNI_writePlayerFinalStatsMsg
  (JNIEnv *, jclass, jint, jint, jint, jstring, jint, jint, jint, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     edu_cs300_MessageJNI
 * Method:    readAtBatPitchResultsMsg
 * Signature: ()Ledu/cs300/AtBatPitchResults;
 */
JNIEXPORT jobject JNICALL Java_edu_cs300_MessageJNI_readAtBatPitchResultsMsg
  (JNIEnv *, jclass);

/*
 * Class:     edu_cs300_MessageJNI
 * Method:    readStringMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_cs300_MessageJNI_readStringMsg
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
